### ISSUE TITLE
Silent Crash

### ISSUE THREAD

**Issue by OxBrutal** [JaxkDev/DiscordBot#74] opened 2022-08-13 09:15 UTC
* Why now discord bot plugin often disable itself?
![Screenshot_20220813-161416](https://user-images.githubusercontent.com/61906304/184477347-76cc7692-f73d-454c-a938-89ae216f79a4.jpg)

**Comment by JaxkDev** [comment] 2022-08-13 09:18
Check the logs yourself in plugin_data or send the file generated from /debugdiscord

**Comment by OxBrutal** [comment] 2022-08-13 09:23
Oke wait

**Comment by OxBrutal** [comment] 2022-08-13 09:33
Here
* https://pastebin.com/2L5MLi1p

**Comment by OxBrutal** [comment] 2022-08-13 10:17
> Check the logs yourself in plugin_data or send the file generated from /debugdiscord

Here
* https://pastebin.com/2L5MLi1p

**Comment by JaxkDev** [comment] 2022-10-13 11:21
https://pastebin.com/rC69QDfv

**Comment by JaxkDev** [comment] 2022-10-13 11:23
Duplicate of #66

**Closed as completed by JaxkDev** 2022-10-13 11:23 UTC
Labels: Priority: Medium, Type: Bug
