### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Altamash347** [JaxkDev/DiscordBot#27] opened 2021-05-07 15:21 UTC
```
[15:19:33] [BotThread thread/CRITICAL]: Client failed to login/connect within 30 seconds, See log file for details.
[15:19:34] [Server thread/INFO]: Disabling DiscordBot v1.0.0
```

**Comment by JaxkDev** [comment] 2021-05-07 15:23
As it says, read the log file for more info...
At least copy the error from the log file it's telling you to go to.

**Comment by JaxkDev** [comment] 2021-05-07 16:45
Duplicate of #8

**Closed by JaxkDev** 2021-05-07 16:45 UTC
