### ISSUE TITLE
Message Attachment content_type error

### ISSUE THREAD

**Issue by Shehab99** [JaxkDev/DiscordBot#55] opened 2022-03-31 08:56 UTC
i tried to send a file .phar and .mcpack and the plugin has been disabled !

**Comment by JaxkDev** [comment] 2022-04-06 13:56
Logs/debugdata is required.

**Comment by JaxkDev** [comment] 2022-04-12 11:15
I can't reproduce, and with no actual data (error messages/stack traces/debug data/logs) I can't do anything.

**Comment by JaxkDev** [comment] 2022-04-12 11:19
```
[2022-04-12T11:17:07.427106+00:00] DiscordThread.CRITICAL: ErrorException: "Undefined property: stdClass::$content_type" (EXCEPTION) in "phar:///Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Bot/ModelConverter.php" at line 267 [] []
[2022-04-12T11:17:07.504371+00:00] DiscordThread.CRITICAL: #0 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Bot/ModelConverter(267): JaxkDev\DiscordBot\Bot\Client->sysErrorHandler(integer 2, string[43] Undefined property: stdClass::$content_type, string[114] phar:///Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-, integer 267) [] []
[2022-04-12T11:17:07.504597+00:00] DiscordThread.CRITICAL: #1 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Bot/ModelConverter(225): JaxkDev\DiscordBot\Bot\ModelConverter::genModelAttachment(object stdClass#1812) [] []
[2022-04-12T11:17:07.504712+00:00] DiscordThread.CRITICAL: #2 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Bot/Handlers/DiscordEventHandler(334): JaxkDev\DiscordBot\Bot\ModelConverter::genModelMessage(object Discord\Parts\Channel\Message#1891) [] []
[2022-04-12T11:17:07.504784+00:00] DiscordThread.CRITICAL: #3 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): JaxkDev\DiscordBot\Bot\Handlers\DiscordEventHandler->onMessageCreate(object Discord\Parts\Channel\Message#1891, object JaxkDev\DiscordBot\Bot\Discord#12, NULL ) [] []
[2022-04-12T11:17:07.504853+00:00] DiscordThread.CRITICAL: #4 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/team-reflex/discord-php/src/Discord/Discord(697): Discord\Discord->emit(string[14] MESSAGE_CREATE, array[3]) [] []
[2022-04-12T11:17:07.504918+00:00] DiscordThread.CRITICAL: #5 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/promise/src/FulfilledPromise(42): Discord\Discord->Discord\{closure}(object Discord\Parts\Channel\Message#1891) [] []
[2022-04-12T11:17:07.504983+00:00] DiscordThread.CRITICAL: #6 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/promise/src/Promise(66): React\Promise\FulfilledPromise->done(object Closure#1886, object Closure#133) [] []
[2022-04-12T11:17:07.505048+00:00] DiscordThread.CRITICAL: #7 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/promise/src/Promise(168): React\Promise\Promise::React\Promise\{closure}(object React\Promise\FulfilledPromise#1864) [] []
[2022-04-12T11:17:07.505112+00:00] DiscordThread.CRITICAL: #8 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/promise/src/Promise(231): React\Promise\Promise->settle(object React\Promise\FulfilledPromise#1864) [] []
[2022-04-12T11:17:07.505178+00:00] DiscordThread.CRITICAL: #9 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/promise/src/Deferred(36): React\Promise\Promise::React\Promise\{closure}(object Discord\Parts\Channel\Message#1891) [] []
[2022-04-12T11:17:07.505242+00:00] DiscordThread.CRITICAL: #10 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate(51): React\Promise\Deferred->resolve(object Discord\Parts\Channel\Message#1891) [] []
[2022-04-12T11:17:07.505328+00:00] DiscordThread.CRITICAL: #11 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/team-reflex/discord-php/src/Discord/Discord(721): Discord\WebSockets\Events\MessageCreate->handle(object Discord\Helpers\Deferred#1895, object stdClass#1983) [] []
[2022-04-12T11:17:07.505407+00:00] DiscordThread.CRITICAL: #12 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/team-reflex/discord-php/src/Discord/Discord(594): Discord\Discord->handleDispatch(object stdClass#1694) [] []
[2022-04-12T11:17:07.505495+00:00] DiscordThread.CRITICAL: #13 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): Discord\Discord->handleWsMessage(object Ratchet\RFC6455\Messaging\Message#1036, object Ratchet\Client\WebSocket#416) [] []
[2022-04-12T11:17:07.505584+00:00] DiscordThread.CRITICAL: #14 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/ratchet/pawl/src/WebSocket(72): Ratchet\Client\WebSocket->emit(string[7] message, array[2]) [] []
[2022-04-12T11:17:07.505651+00:00] DiscordThread.CRITICAL: #15 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(object Ratchet\RFC6455\Messaging\Message#1036, object Ratchet\RFC6455\Messaging\MessageBuffer#273) [] []
[2022-04-12T11:17:07.505913+00:00] DiscordThread.CRITICAL: #16 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData(string[994] .~..{"t":"MESSAGE_CREATE","s":25,"op":0,"d":{"type":0,"tts":false,"timestamp":"2) [] []
[2022-04-12T11:17:07.506091+00:00] DiscordThread.CRITICAL: #17 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData(string[994] .~..{"t":"MESSAGE_CREATE","s":25,"op":0,"d":{"type":0,"tts":false,"timestamp":"2) [] []
[2022-04-12T11:17:07.506431+00:00] DiscordThread.CRITICAL: #18 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/stream/src/Util(71): Evenement\EventEmitter->emit(string[4] data, array[1]) [] []
[2022-04-12T11:17:07.506628+00:00] DiscordThread.CRITICAL: #19 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): React\Stream\Util::React\Stream\{closure}(string[994] .~..{"t":"MESSAGE_CREATE","s":25,"op":0,"d":{"type":0,"tts":false,"timestamp":"2) [] []
[2022-04-12T11:17:07.506714+00:00] DiscordThread.CRITICAL: #20 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/stream/src/DuplexResourceStream(196): Evenement\EventEmitter->emit(string[4] data, array[1]) [] []
[2022-04-12T11:17:07.506798+00:00] DiscordThread.CRITICAL: #21 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/event-loop/src/StreamSelectLoop(246): React\Stream\DuplexResourceStream->handleData(resource Resource id #325) [] []
[2022-04-12T11:17:07.506881+00:00] DiscordThread.CRITICAL: #22 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/react/event-loop/src/StreamSelectLoop(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(integer 49999) [] []
[2022-04-12T11:17:07.506969+00:00] DiscordThread.CRITICAL: #23 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/vendor/team-reflex/discord-php/src/Discord/Discord(1368): React\EventLoop\StreamSelectLoop->run() [] []
[2022-04-12T11:17:07.507116+00:00] DiscordThread.CRITICAL: #24 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Bot/Client(111): Discord\Discord->run() [] []
[2022-04-12T11:17:07.507227+00:00] DiscordThread.CRITICAL: #25 /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/DiscordBot_dev-28.phar/src/Communication/BotThread(51): JaxkDev\DiscordBot\Bot\Client->__construct(object JaxkDev\DiscordBot\Communication\BotThread#1, array[4]) [] []
[2022-04-12T11:17:07.507389+00:00] DiscordThread.CRITICAL: #26 (): JaxkDev\DiscordBot\Communication\BotThread->run() [] []
```

**Comment by JaxkDev** [comment] 2022-05-08 17:11
Fixed, will be in next patch/minor release.

**Closed as completed by JaxkDev** 2022-05-08 17:11 UTC
Labels: Status: Fixed, Type: Bug
